# Creating a Logistic Regression to predict Absenteeism

## Import the relevant libraries

In [1]:
import pandas as pd
import numpy as np

## Load the data

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month_value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## Create the targets

In [3]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [5]:
data_preprocessed["Excessive Absenteeism"] = targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month_value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## A comment on the targets

In [6]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [7]:
data_with_targets = data_preprocessed.drop(["Absenteeism Time in Hours",  "Day of the Week", "Distance to Work",
       "Daily Work Load Average"], axis = 1)

In [8]:
data_with_targets is data_preprocessed

False

In [9]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month_value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## Select the imputs for the regression

In [10]:
data_with_targets.shape

(700, 12)

In [11]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month_value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [12]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

## Standardize the data

In [13]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [14]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # with some columns 'twist'
        self.copy = copy
        self.columns = columns
        self.with_mean = with_mean
        self.with_std = with_std
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy=self.copy, with_mean=self.with_mean, with_std=self.with_std)
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [15]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month_value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [16]:
#columns_to_scale = (['Month_value', 'Day of the Week', 'Transportation Expense', 'Distance to Work',
#       'Age', 'Daily Work Load Average', 'Body Mass Index','Children', 'Pets'])

columns_to_omit = ["Reason_1", "Reason_2", "Reason_3", "Reason_3", "Education"]

In [17]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [18]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [19]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\danie\anaconda3\envs\py3-TF2.0\lib\site-packages\numpy\core\fromnumeric.py:3785: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


CustomScaler(columns=['Reason_4', 'Month_value', 'Transportation Expense',
                      'Age', 'Body Mass Index', 'Children', 'Pets'])

In [20]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [21]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month_value  \
0           0         0         0  0.821365     0.182726   
1           0         0         0 -1.217485     0.182726   
2           0         0         0  0.821365     0.182726   
3           1         0         0 -1.217485     0.182726   
4           0         0         0  0.821365     0.182726   
..        ...       ...       ...       ...          ...   
695         1         0         0 -1.217485    -0.388293   
696         1         0         0 -1.217485    -0.388293   
697         1         0         0 -1.217485    -0.388293   
698         0         0         0  0.821365    -0.388293   
699         0         0         0  0.821365    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [22]:
scaled_inputs.shape

(700, 11)

## Split the data into train & test and shuffle

### Import the relevant module

In [23]:
from sklearn.model_selection import train_test_split

### Split

In [24]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [25]:
print (x_train.shape, y_train.shape)

(560, 11) (560,)


In [26]:
print (x_test.shape, y_test.shape)

(140, 11) (140,)


## Logistic regression with sklearn

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### Training the model

In [28]:
reg = LogisticRegression()

In [29]:
reg.fit(x_train, y_train)

LogisticRegression()

In [30]:
reg.score(x_train, y_train)

0.7767857142857143

### Manually check the accuracy

In [31]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [32]:
np.sum(model_outputs==y_train)

435

In [33]:
model_outputs.shape[0]

560

In [34]:
np.sum(model_outputs==y_train) / model_outputs.shape[0]

0.7767857142857143

### Finding the intercept and coefficients

In [35]:
reg.intercept_

array([-1.17814662])

In [36]:
reg.coef_

array([[ 2.88832229,  0.99608112,  3.18783757,  0.46007664,  0.16021734,
         0.60752392, -0.16791192,  0.2803855 , -0.2017468 ,  0.35076664,
        -0.27715416]])

In [37]:
feature_name = unscaled_inputs.columns.values

In [38]:
summary_table = pd.DataFrame (columns = ["Feature name"], data = feature_name)

summary_table["Coefficient"] = np.transpose(reg.coef_)

In [39]:
summary_table

Feature name  Coefficient
0                 Reason_1     2.888322
1                 Reason_2     0.996081
2                 Reason_3     3.187838
3                 Reason_4     0.460077
4              Month_value     0.160217
5   Transportation Expense     0.607524
6                      Age    -0.167912
7          Body Mass Index     0.280386
8                Education    -0.201747
9                 Children     0.350767
10                    Pets    -0.277154

In [40]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ["Intercept", reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -1.178147
1                 Reason_1     2.888322
2                 Reason_2     0.996081
3                 Reason_3     3.187838
4                 Reason_4     0.460077
5              Month_value     0.160217
6   Transportation Expense     0.607524
7                      Age    -0.167912
8          Body Mass Index     0.280386
9                Education    -0.201747
10                Children     0.350767
11                    Pets    -0.277154

### Interpreting the coefficients

In [41]:
summary_table["Odds_ratio"] = np.exp(summary_table.Coefficient)

In [42]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -1.178147    0.307849
1                 Reason_1     2.888322   17.963147
2                 Reason_2     0.996081    2.707650
3                 Reason_3     3.187838   24.235962
4                 Reason_4     0.460077    1.584195
5              Month_value     0.160217    1.173766
6   Transportation Expense     0.607524    1.835880
7                      Age    -0.167912    0.845428
8          Body Mass Index     0.280386    1.323640
9                Education    -0.201747    0.817302
10                Children     0.350767    1.420156
11                    Pets    -0.277154    0.757938

In [43]:
summary_table.sort_values("Odds_ratio", ascending = False)

Feature name  Coefficient  Odds_ratio
3                 Reason_3     3.187838   24.235962
1                 Reason_1     2.888322   17.963147
2                 Reason_2     0.996081    2.707650
6   Transportation Expense     0.607524    1.835880
4                 Reason_4     0.460077    1.584195
10                Children     0.350767    1.420156
8          Body Mass Index     0.280386    1.323640
5              Month_value     0.160217    1.173766
7                      Age    -0.167912    0.845428
9                Education    -0.201747    0.817302
11                    Pets    -0.277154    0.757938
0                Intercept    -1.178147    0.307849

### Testing the model

In [45]:
reg.score(x_test, y_test)

0.75

In [46]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.71195804, 0.28804196],
       [0.58423743, 0.41576257],
       [0.43683334, 0.56316666],
       [0.78089026, 0.21910974],
       [0.08374415, 0.91625585],
       [0.33638788, 0.66361212],
       [0.30035259, 0.69964741],
       [0.13244406, 0.86755594],
       [0.78565531, 0.21434469],
       [0.74798369, 0.25201631],
       [0.4909974 , 0.5090026 ],
       [0.22229962, 0.77770038],
       [0.07210376, 0.92789624],
       [0.72849462, 0.27150538],
       [0.31159392, 0.68840608],
       [0.54358098, 0.45641902],
       [0.54802745, 0.45197255],
       [0.53667409, 0.46332591],
       [0.40090984, 0.59909016],
       [0.05425703, 0.94574297],
       [0.69878026, 0.30121974],
       [0.78089026, 0.21910974],
       [0.42198446, 0.57801554],
       [0.42198446, 0.57801554],
       [0.25197465, 0.74802535],
       [0.74463771, 0.25536229],
       [0.50696292, 0.49303708],
       [0.85554685, 0.14445315],
       [0.20670584, 0.79329416],
       [0.78089026, 0.21910974],
       [0.

In [47]:
predicted_proba.shape

(140, 2)

In [48]:
predicted_proba[:,1]

array([0.28804196, 0.41576257, 0.56316666, 0.21910974, 0.91625585,
       0.66361212, 0.69964741, 0.86755594, 0.21434469, 0.25201631,
       0.5090026 , 0.77770038, 0.92789624, 0.27150538, 0.68840608,
       0.45641902, 0.45197255, 0.46332591, 0.59909016, 0.94574297,
       0.30121974, 0.21910974, 0.57801554, 0.57801554, 0.74802535,
       0.25536229, 0.49303708, 0.14445315, 0.79329416, 0.21910974,
       0.37211182, 0.67761864, 0.68371992, 0.53183228, 0.21910974,
       0.53767634, 0.22214858, 0.73268996, 0.40847083, 0.60879133,
       0.21138359, 0.4515426 , 0.2383582 , 0.37852985, 0.82812696,
       0.56173302, 0.69003554, 0.28804196, 0.22042242, 0.20385876,
       0.57657772, 0.31161297, 0.66361212, 0.27116013, 0.83342552,
       0.43814206, 0.88198493, 0.23223158, 0.31529253, 0.3252502 ,
       0.6995057 , 0.65332553, 0.29410128, 0.78865325, 0.20859856,
       0.26964979, 0.07967023, 0.22214858, 0.72841658, 0.30916546,
       0.22214858, 0.27308814, 0.90465592, 0.46466592, 0.60478

## Save the model

In [49]:
import pickle

In [50]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [52]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)